### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by cesagonchu** [mambax7/wfdownloads#3]
When I want to install the module wfdownloads I get this error:

> Error: Undefined constant "CO_WFDOWNLOADS_BLOCKS" in file /modules/wfdownloads/admin/menu.php line 145

___

My config
Apache/2.4.52 (Ubuntu)
PHP version 8.1.2-1ubuntu2.10
MYSQL 8.0.32-0ubuntu0.22.04.2
wfdownloads 3.30.0 (Mamba version)
XOOPS 2.5.11-Beta2 (latest version)

**Comment by mambax7** [comment]
Can you check if you French translation of "common.php" has the definition:
```php
\define('CO_' . $moduleDirNameUpper . '_' . 'BLOCKS', 'Blocks Admin');
```

**Comment by cesagonchu** [comment]
All are in English. I always do my tests with English versions.

**Comment by cesagonchu** [comment]
That's strange, yesterday when I downloaded the module, there was no `"\" `in front of the define
I'll test with this new module download.

**Comment by cesagonchu** [comment]
The installation was done without problems.
