### ISSUE TITLE
class configurator not found

### ISSUE THREAD

**Issue by cesagonchu** [mambax7/wfdownloads#4]
I get an error when I go to wfdownloads admin side (/modules/wfdownloads/admin/index.php):

> Error: Class "Configurator" not found in file /modules/wfdownloads/admin/index.php line 164

___

My config (all in English)

Apache/2.4.52 (Ubuntu)
PHP version 8.1.2-1ubuntu2.10
MYSQL 8.0.32-0ubuntu0.22.04.2
wfdownloads 3.30.0 (Mamba version)
XOOPS 2.5.11-Beta2 (latest version)

**Comment by mambax7** [comment]
This should be now fixed in https://github.com/mambax7/wfdownloads/commit/4e53b7311bdfbba4e8737f7c02344503244793e1
